import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import Head from 'next/head';

import { Question } from 'types';

import axios from 'axiosInstance';
import Card from 'components/Card';
import Grid from 'components/Grid';
import Container from 'components/Container';

const Question = () => {
  const router = useRouter();
  const { questionid } = router.query;

  const [question, setQuestion] = useState<Question>();

  useEffect(() => {
    const getQuestions = async () => {
      const { data } = await axios(`questions/${questionid}`);
      setQuestion(data);
    };
    getQuestions();
  }, [questionid]);

  return (
    <div>
      <Head>
        <title>{question?.question}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <h1>{question?.question}</h1>
          <Grid gridTemplateColumns={['auto', 'auto auto', 'auto auto auto', 'auto auto auto auto']}>
            {question?.choices.map((item, index) => (
              <Card key={`question-${index}`}>{item.choice}</Card>
            ))}
          </Grid>
        </Container>
      </main>
    </div>
  );
};

export default Question;
