import type { NextPage } from 'next';
import Head from 'next/head';

import Container from 'components/Container';


const NewQuestion: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yemek.com Test Case</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          Selam
        </Container>
      </main>
    </div>
  );
};

export default NewQuestion;
