import type { AppProps } from 'next/app';
import Head from 'next/head';
import { GlobalStyles, Container } from 'skeleton-responsive-ui';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <GlobalStyles />
        <Container>
          <Component {...pageProps} />
        </Container>
      </main>
    </>
  );
}

export default MyApp;
