import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import { useState, useEffect } from 'react';

import { Question } from 'types';

import axios from 'axiosInstance';
import Card from 'components/Card';
import Grid from 'components/Grid';
import Container from 'components/Container';

const Home: NextPage = () => {
  const [questions, setQuestions] = useState<Question[]>([]);
  useEffect(() => {
    const getQuestions = async () => {
      const { data } = await axios('questions?page=1');
      setQuestions(data);
    };
    getQuestions();
  }, []);

  return (
    <div>
      <Head>
        <title>Yemek.com Test Case</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <h1>Yemek.com Test Case</h1>
          <Grid gridTemplateColumns={['auto', 'auto auto', 'auto auto auto', 'auto auto auto auto']}>
            {questions.map((item, index) => (
              <Link href={item.url}>
                <a>
                  <Card key={`question-${index}`}>{item.question}</Card>
                </a>
              </Link>
            ))}
          </Grid>
        </Container>
      </main>
    </div>
  );
};

export default Home;
