import type { NextPage } from 'next';
import Head from 'next/head';

import Container from 'components/Container';
import Image from 'next/image';
import QuestionList from 'containers/QuestionList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yemek.com Test Case</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <div style={{ display: 'flex', alignItems: 'center' }}>
            <span style={{ marginRight: "1rem" }}>
              <Image src='/logo.svg' height={50} width={120} alt='yemek.com ikonu' priority />
            </span>
            <h1>Test Case</h1>
          </div>
          <QuestionList />
        </Container>
      </main>
    </div>
  );
};

export default Home;
